### ISSUE TITLE
project brain dump

### ISSUE THREAD

**Issue by DraconPern** [alexsharoff/pcsx2-online#16]
Hello, we are two people who's interested in trying to integrate this back into pcsx2 proper.  Is there any chance we can do a brain dump?  The code is highly async and even by stepping through the code, there's some parts that are still a mystery.  Also, it would be nice to see if there was a road map that we can just pick up from. Thanks!

**Comment by YungMoniCA1** [comment]
Good luck trying to get this asshole coder back in contact.

**Comment by duckman963** [comment]
He's really not an asshole, hes responded to me multiple times.  He said he was done with the project.

**Comment by Sergynx** [comment]
I'd love seeing this project back in development,. At least give these guys a chance

**Comment by DraconPern** [comment]
Just want to give people who check this issue a heads up.  We have been working on it at https://github.com/SmileTheory/pcsx2
