### ISSUE TITLE
PCSX2 Implementing P2P Netcode and bezels for 4:3 aspect ratio. Capnet Club Discord

### ISSUE THREAD

**Issue by BevP90** [alexsharoff/pcsx2-online#17]
I go by BevP902 on Discord and I run the Capnet Club group where we play CVS2, 3rd Strike, Hyper SFII, MVC2 and Capcom Fighting Evolution online. I'm looking to work with someone so we can improve this delay based netcode. If anyone can lend a hand in the project, please let me know. The group currently stands at 440 members and would love to see better online play. Thanks. Youtube for gameplay videos of current netplay - https://www.youtube.com/channel/UCtZWLtMv5B2Vwz9b1nYVnOQ
[https://discord.gg/2fQ773D](url) Is the link to the Discord.

**Comment by BevP90** [comment]
We're looking to implement these features...
- Rollback netcode instead of Delay based netcode - We can still use the IP connection system.
- Have artwork bezels on the sides of the screen - I'll provide my own art work since games run in 4:3.
- Display the usernames from the netplay box - Usernames are typed in before a match, and this information is saved usually so it shouldn't be too hard to implement. 
Here are some mockup screenshots.
![Mockup](https://user-images.githubusercontent.com/29954013/66162108-9c2ec500-e625-11e9-819c-882ca4d1c9cc.png)
![3s](https://user-images.githubusercontent.com/29954013/66162130-a6e95a00-e625-11e9-84a4-a06401b1e214.png)

**Comment by BevP90** [comment]
@alexsharoff

**Comment by alexsharoff** [comment]
Woah, was not expected this project to still be relevant after all these years.

Please let me regroup a bit, my PC is going to be in repair for another week and I haven't looked at this project for at least 6 years, it’s going to take a while.

It’s going to be really hard to bring rollbacks into pcsx2. Hell, even current delay-based implementation is far from being done and stable. If we’re talking about 3rd Strike, then GGPO ancestors such as (IIRC) Fightcade cannot be beat currently (or ever, imo).

**Comment by BevP90** [comment]
@alexsharoff Did not expect you to reply, thanks for looking at this man! Yeah I'm trying to do something new. My Discord group playing these games is starting to take off, doing really well so far and getting a lot of play with CVS2, Hyper SF2 and 3rd Strike using your build of netplay. Do you think we could do something similar to what Dolphin does with a P2P connection? That uses IP Addresses and the other option in Dolphin is called traversal server I think? Off the top of my head. I've setup a bounty to pay someone if they could code this. My group would take off with improved netcode and adding in bezels. So far your work is excellent though.

**Comment by BevP90** [comment]
@alexsharoff Turns out the new GGPO SDK and license is free, do you think it'd be possible to use this?

**Comment by alexsharoff** [comment]
Rollbacks are out of the question (at least for me), but GGPO seems to require some rollback implementation.

**Comment by BevP90** [comment]
I think we'll stick to delay for now, your netcode is excellent but if you could improve it I'll throw you some money

**Comment by alexsharoff** [comment]
I've migrated my changes to upstream PCSX2 codebase as it was at the moment of my original fork.
Check https://github.com/alexsharoff/pcsx2, branch 'netplay'.

Also, I've added boost subset to 3rd party libraries, so it should build out of the box now. Please try and report if you have any problems. You have to use Visual Studio 2010, though.

I don't see myself picking up where I left off with this project. However, I'll try to create a comprehensive issue list in the new repo sometime soon, so that all known issues are documented. Current repository will probably just link to the new one.
