### ISSUE TITLE
Analog sticks aren't working in the newer versions

### ISSUE THREAD

**Issue by Jayle555** [alexsharoff/pcsx2-online#7]
I've tried some older versions of pcsx2o and they seem to work fine, but with the newest version I haven't managed to get them to work after the game boots up. If I boot to the bios they work fine, but as soon as the game loads they no longer work. 

The analog sticks seem to work in the September 18th build,  and the build from November 12th, but anything after that I haven't been able to get them to work.

I was wondering if you had any work arounds for this, or any plans to fix it.  I'd use the November build, but it just closes when someone connects to my netplay session.

Thanks.

**Comment by Kyraminol** [comment]
Any bump on this? I searched the net in his entirely and no one has fixed this.. please can you give us november build? I searched even in readme commits and it was deleted from mediafire..

**Comment by Xlaits** [comment]
I'm also having this same issue. However, I have noticed that the BIOS recognizes and uses the sticks, but my games don't? Maybe trying to boot full instead of fast would help... if we could choose that at all...
