### ISSUE TITLE
PCSX2 Netplay: Timeout while synchonizing memory cards

### ISSUE THREAD

**Issue by Kazuma88** [alexsharoff/pcsx2-online#8]
While trying to join to a host i got this message: Netplay: Timeout while synchonizing memory cards".Even with deleted/disabled/formated memory cards i got the same message.What should i do?I heard there is a new version which no longer requires memory card synchronisation from both players however i cant find that version,it has been deleted.What should i do?

**Comment by apathy27** [comment]
hey Kazuma88, can u tell me where u got that version of pcsx2 of urs from? im also getting an issue with the memcard sync

**Comment by luigi91c** [comment]
Who wants to play online with me? The Last updated version of pcsx2 online is in Facebook page PCSX2 1.6.0
