### ISSUE TITLE
King of Fighters 98:Ultimate no load on netplay

### ISSUE THREAD

**Issue by Eishi** [alexsharoff/pcsx2-online#9]
Hello.  First off, great work.  Been playing for several days, everything works great for the most part.  KOF2k2UM runs great, XI desyncs every now and then, as you've noted, CvS2 works well too, minus some annoying screen shaking, which I'm sure can be fixed, but KOF98UM does not load.

Here's the weird thing: it works perfect offline.  But come netplay, just a black screen.  Delay notice, memory card sync, then nothing.  Just a black screen.

If you're able to, think you could take a look at it?  Thanks!

Using your latest release.

**Comment by feikname** [comment]
I know this is unmainted, but as a note: This also happens with Bleach Blade Battlers 2nd.
